version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: db_capstone
      MYSQL_ROOT_PASSWORD: 123456789
      BASE_URL: http://localhost:8080
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dockervu
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: springboot_capstone
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_capstone
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456789
      AZURE_STORAGE_ACCOUNT_KEY: Mmheb6KKumzJiWclGO937G5pEqGihUBeuMYhwXixVnCLx13dguUeCbsX5J8OhZIHuHrCiT/LD96Y+AStjTASxQ==
      FACEBOOK_CLIENT_ID: 3733164560230312
      FACEBOOK_CLIENT_SECRET: f28538ebb45667825aeeb30333df17ac
      GOOGLE_CLIENT_ID: 684504390647-3n31glri0v6tt6ackrf2rq1hfpsb6m23.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - dockervu

volumes:
  mysql-data:

networks:
  dockervu:
    driver: bridge