@startuml Use Case - Quản lý Sản phẩm (Chủ Cửa Hàng)

left to right direction
skinparam packageStyle rect
skinparam backgroundColor #EEEEEE
skinparam actorBackgroundColor #AAAAAA
skinparam useCaseBackgroundColor #BBBBBB
skinparam arrowColor #333333
skinparam defaultFontName Arial
skinparam defaultFontSize 10
skinparam shadowing true

actor "Chủ Cửa Hàng" as Owner

usecase "Đăng nhập Hệ thống" as Login

package "Quản lý Sản phẩm" {
  usecase "Quản lý Sản phẩm" as ManageProducts
  usecase "Thêm sản phẩm mới" as AddProduct
  usecase "Cập nhật thông tin sản phẩm" as UpdateProductInfo
  usecase "Quản lý biến thể sản phẩm" as ManageVariants
  usecase "Quản lý hình ảnh sản phẩm" as ManageImages
  usecase "Quản lý mô tả sản phẩm" as ManageDescription
}

Owner -- (Login)
Owner -- (ManageProducts)
(ManageProducts) .> (AddProduct) : include
(ManageProducts) .> (UpdateProductInfo) : include
(ManageProducts) .> (ManageVariants) : include
(ManageProducts) .> (ManageImages) : include
(ManageProducts) .> (ManageDescription) : include

@enduml