@startuml Use Case - Quản lý Thuộc tính (Chủ Cửa Hàng)

left to right direction
skinparam packageStyle rect
skinparam backgroundColor #EEEEEE
skinparam actorBackgroundColor #AAAAAA
skinparam useCaseBackgroundColor #BBBBBB
skinparam arrowColor #333333
skinparam defaultFontName Arial
skinparam defaultFontSize 10
skinparam shadowing true

actor "Chủ Cửa Hàng" as Owner

usecase "Đăng nhập Hệ thống" as Login

package "Quản lý Thuộc tính" {
  usecase "Quản lý Thuộc tính" as ManageAttributes
  usecase "Quản lý màu sắc" as ManageColors
  usecase "Quản lý kích thước" as ManageSizes
}

Owner -- (Login)
Owner -- (ManageAttributes)
(ManageAttributes) .> (ManageColors) : include
(ManageAttributes) .> (ManageSizes) : include

@enduml