@startuml Use Case - Quản lý Danh mục (Chủ Cửa Hàng)

left to right direction
skinparam packageStyle rect
skinparam backgroundColor #EEEEEE
skinparam actorBackgroundColor #AAAAAA
skinparam useCaseBackgroundColor #BBBBBB
skinparam arrowColor #333333
skinparam defaultFontName Arial
skinparam defaultFontSize 10
skinparam shadowing true

actor "Chủ Cửa Hàng" as Owner

usecase "Đăng nhập Hệ thống" as Login

package "Quản lý Danh mục" {
  usecase "Quản lý Danh mục" as ManageCategories
  usecase "Thêm/Sửa/Xóa danh mục" as ManageCategory
  usecase "Quản lý thương hiệu" as ManageBrand
  usecase "Quản lý bộ sưu tập" as ManageCollection
}

Owner -- (Login)
Owner -- (ManageCategories)
(ManageCategories) .> (ManageCategory) : include
(ManageCategories) .> (ManageBrand) : include
(ManageCategories) .> (ManageCollection) : include

@enduml