server:
  port: 8080
spring:
  application:
    name: capstone
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://dbcapstone.mysql.database.azure.com:3306/db_capstone}
#    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/db_capstone}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME:mysqladmin}
    password: ${SPRING_DATASOURCE_PASSWORD:Admin123}
#    username: ${SPRING_DATASOURCE_USERNAME:root}
#    password: ${SPRING_DATASOURCE_PASSWORD:123456789}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.show_sql: true
    open-in-view: false
  security:
    jwt:
      signerKey: ${JWT_KEY:W31fqJQUxdNSy/Y+F+RFsa/Zi4hx3sX2tfRH/dAk/0312mbKCFpdljSyUkeE59vxGYdSPYIAW2UW+pExDCD+1Q==}
      valid-duration: 86400
      refreshable-duration: 86400
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code
            client-name: google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://accounts.google.com/o/oauth2/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  jackson:
    serialization:
      fail-on-empty-beans: false
