server:
  port: 8080
  address:  192.168.1.40
spring:
  application:
    name: capstone
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/db_capstone
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      minimum-idle: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.show_sql: true
  security:
    jwt:
      signerKey: "W31fqJQUxdNSy/Y+F+RFsa/Zi4hx3sX2tfRH/dAk/0312mbKCFpdljSyUkeE59vxGYdSPYIAW2UW+pExDCD+1Q=="
      valid-duration: 86400
      refreshable-duration: 86400
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client.id}
            client-secret: ${google.client.secret}
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code
            client-name: google
          facebook:
            client-id: ${facebook.client.id}
            client-secret: ${facebook.client.secret}
            scope:
              - email
              - public_profile
            authorization-grant-type: authorization_code
            client-name: facebook
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://accounts.google.com/o/oauth2/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

          facebook:
            authorization-uri: https://www.facebook.com/v2.8/dialog/oauth
            token-uri: https://graph.facebook.com/v2.8/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,first_name,last_name
            user-name-attribute: id
  jackson:
    serialization:
      fail-on-empty-beans: false
