name: Build and Deploy Docker to Azure VM

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub (optional)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t springboot_capstone .

      - name: Save Docker image to tar file
        run: |
          docker save springboot_capstone > springboot_capstone.tar

      - name: Copy Docker image to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 20.3.131.196
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "springboot_capstone.tar"
          target: "/home/${{ secrets.SSH_USER }}/"

      - name: SSH and deploy on remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 20.3.131.196
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            script: |
            # Tạo Docker network nếu chưa có
            docker network inspect dockervu >/dev/null 2>&1 || docker network create dockervu
            
            # Start MySQL container nếu chưa có
            if [ -z "$(docker ps -a -q -f name=mysql)" ]; then
            echo "MySQL container not found. Creating one..."
            docker run -d \
            --name mysql \
            --network dockervu \
            -e MYSQL_DATABASE=db_capstone \
            -e MYSQL_ROOT_PASSWORD=123456789 \
            -p 3307:3306 \
            -v mysql-data:/var/lib/mysql \
            mysql:8.0
            else
            echo "MySQL container already exists."
            docker start mysql || true
            fi
            
            # Kiểm tra trạng thái MySQL container
            # Stop và remove container nếu đang chạy
            if [ "$(docker ps -q -f name=springboot_capstone)" ]; then
              docker stop springboot_capstone
            fi
            if [ "$(docker ps -a -q -f name=springboot_capstone)" ]; then
              docker rm springboot_capstone
            fi

            # Xóa image cũ nếu có
            docker rmi springboot_capstone || true

            # Load lại image từ tar
            docker load < springboot_capstone.tar
            
            # Chạy container mới trong network 'dockervu'
            docker run -d --name springboot_capstone \
              --network dockervu \
              -p 8080:8080 \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/db_capstone \
              -e SPRING_DATASOURCE_USERNAME=root \
              -e SPRING_DATASOURCE_PASSWORD=123456789 \
              -e AZURE_STORAGE_ACCOUNT_KEY="${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" \
              -e FACEBOOK_CLIENT_ID="${{ secrets.FACEBOOK_CLIENT_ID }}" \
              -e FACEBOOK_CLIENT_SECRET="${{ secrets.FACEBOOK_CLIENT_SECRET }}" \
              -e GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
              -e GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
              springboot_capstone
